version: "3"
name: deemix-for-lidarr
services:
    deemix-test:
        image: codefaux/deemix-for-lidarr
        container_name: deemix
        environment:
            - PUID:100
            - PGID:99
        volumes:
            - /docker/deemix/downloads:/downloads
            - /docker/deemix/config:/deemix-gui/config
        ports:
            - 6595:6595
        restart: unless-stopped
